### ISSUE TITLE
breaks on new highline

### ISSUE THREAD

**Issue by bootstraponline** [zwily/aws-keychain-util#17]
```
$ aws-creds shell me
/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2157:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ff4d600fef0 highline-1.7.8> (NoMethodError)
	from /.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1056:in `find_active_stub_by_path'
	from /.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:63:in `require'
	from /.rvm/gems/ruby-2.2.3/gems/highline-1.7.8/lib/highline.rb:15:in `<top (required)>'
	from /.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:119:in `require'
	from /.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:119:in `require'
	from /.rvm/gems/ruby-2.2.3/gems/aws-keychain-util-0.0.12/bin/aws-creds:8:in `<top (required)>'
	from /.rvm/gems/ruby-2.2.3/bin/aws-creds:23:in `load'
	from /.rvm/gems/ruby-2.2.3/bin/aws-creds:23:in `<main>'
	from /.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by bootstraponline** [comment]
I wonder if it's a rubygems issue.
https://github.com/rubygems/rubygems/issues/1420

**Comment by tristanmorgan** [comment]
Hi @bootstraponline, I know its been a while since you had this error, sorry for the delay. I have tried but failed to replicate the issue you are having. I see you are using RVM, can you confirm if a different ruby version say 'ruby 2.0.0p648' has this error too?

T.

**Comment by bootstraponline** [comment]
I updated rubygems and moved to rbenv, haven't seen this error again. I think it was an issue with rubygems.
